### ISSUE TITLE
Unable to use import opus_miner

### ISSUE THREAD

**Issue by NitakshiSood** [situsnow/opusminer#1]
Hi,
I tried using this implementation of opus miner in python however, I get this error "from opusminer.cpplib.boostpython3 import opus_miner" .
Could you please suggest, any workaround for this in windows.

Thanks in advance!!

**Comment by situsnow** [comment]
Hi nitakshi,

The error msg is not complete, could you copy the full msg? And may I know if you follow the README to install correspondent packages in windows?

Cheers,
Snow

**Comment by NitakshiSood** [comment]
Hello Snow,
Thank for replying.
Here is the complete error message when I try to run TestOpusMiner.py file.
Traceback (most recent call last):
  File "~/opusminer/Sample/TestOpusMiner.py", line 4, in <module>
    from opusminer.OpusMiner import *
  File "D:\opusminer\OpusMiner.py", line 9, in <module>
    from opusminer.cpplib.boostpython3 import opus_miner
builtins.ImportError: cannot import name 'opus_miner' from 'opusminer.cpplib.boostpython3'

Seems like it is not able to import opus_miner.so file!! Could you please suggest a possible solution?
Thank you soo much!!

Best,
Nitakshi

**Comment by situsnow** [comment]
Hi Nitakshi,

I assumed something wrong with the boost-python. But I haven't maintain the program for long time. Have you tried to run correspondent commands in windows to install boost-python? The commands in Mac will be like this:
brew install boost
brew install boost-python
brew install boost-python3
brew install llvm --universal

As I am not familiar with install boost-python in Windows, you might need to google it and try. Hope this helps.

Cheers,
Snow
